# qemu configuration toml file

bin_path = "qemu-system-x86_64"

name = "myQemu"

cpu_model = "qemu64"

vga = "std"

global_params = ""

bios = ""

no_graphic = true

[kernel]
path = "/usr/share/kata-containers/vmlinuz.container"
# initrd_path = "/usr/share/kata-containers/kata-containers.img"
initrd_path = ""
params = "console=ttyS0"

[memory]
size = "1G"
slots = 0
max_memory = ""
path = ""

[smp]
cpus = 4
cores = 2
threads = 1
sockets = 4
max_cpus = 8

[machine]
machine_type = ""
acceleration = ""
options = ""
